#include <SFML/Graphics.hpp>
#include "GameWorld.h"
#include "Tiles.cpp"
#include <vector>

GameWorld::GameWorld() {
    tiles.clear();
    mapX = 32;
    mapY = 24;
    setUpTiles();
    setUpDeco();
}

GameWorld::~GameWorld() {
    // Libérer la mémoire des objets GameTile
    for (auto row : tiles) {
        for (auto tile : row) {
            delete tile;
        }
    }

    // Libérer la mémoire des objets GameTile dans le vecteur deco
    for (auto tile : deco) {
        delete tile;
    }
}

bool GameWorld::checkCollision(const sf::FloatRect& bordure) const {
    for (int i = 0; i < mapY; i++) {
        for (int j = 0; j < mapX; j++) {
            if (!tiles[i][j]->isPassable) {
                if (bordure.intersects(tiles[i][j]->sprite.getGlobalBounds())) {
                    return true;
                }
            }
        }
    }

    for (const GameTile* decoElement : deco) {
        if (!decoElement->isPassable) {
            if (bordure.intersects(decoElement->sprite.getGlobalBounds())) {
                return true;
            }
        }
    }
    return false;
}

void GameWorld::setUpDeco() 
{
    //arbre
    deco.push_back(new GameTile("./Texture/map/Arbre/1.png", 400, 300, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/1.png", 0, 600, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/1.png", 0, 650, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/1.png", 0, 700, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/1.png", 0, 750, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/1.png", 50, 750, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/1.png", 100, 750, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/1.png", 150, 750, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/1.png", 600, 0, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/1.png", 650, 0, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/1.png", 700, 0, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/1.png", 750, 0, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/1.png", 800, 0, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/1.png", 850, 0, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/1.png", 900, 0, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/2.png", 300, 0, false));
    int posx=13*50 , posy=15*50;
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/1.png", posx, posy, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/2.png", posx+50, posy, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/3.png", posx+100, posy, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/4.png", posx, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/5.png", posx+50, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/6.png", posx+100, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/7.png", posx, posy+100, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/8.png", posx+50, posy+100, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/9.png", posx+100, posy+100, true));
    posx=14*50; posy=13*50 ;
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/1.png", posx, posy, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/2.png", posx+50, posy, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/3.png", posx+100, posy, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/4.png", posx, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/5.png", posx+50, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/6.png", posx+100, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/7.png", posx, posy+100, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/8.png", posx+50, posy+100, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/9.png", posx+100, posy+100, true));
    posx=11*50; posy=11*50;
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/1.png", posx, posy, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/2.png", posx+50, posy, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/3.png", posx+100, posy, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/4.png", posx, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/5.png", posx+50, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/6.png", posx+100, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/7.png", posx, posy+100, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/8.png", posx+50, posy+100, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/9.png", posx+100, posy+100, true));
    posx=10*50; posy=14*50;
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/1.png", posx, posy, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/2.png", posx+50, posy, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/3.png", posx+100, posy, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/4.png", posx, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/5.png", posx+50, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/6.png", posx+100, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/7.png", posx, posy+100, true));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/8.png", posx+50, posy+100, false));
    deco.push_back(new GameTile("./Texture/map/Arbre/Arbre1/9.png", posx+100, posy+100, true));

    //maison
    posx=25*50; posy=14*50;
    deco.push_back(new GameTile("./Texture/map/Maison/Maison1/1.png", posx, posy, true));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison1/2.png", posx+50, posy, true));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison1/3.png", posx, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison1/4.png", posx+50, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison1/5.png", posx, posy+100, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison1/6.png", posx+50, posy+100, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison1/7.png", posx, posy+150, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison1/8.png", posx+50, posy+150, false));
    posx=29*50; posy=13*50;
    deco.push_back(new GameTile("./Texture/map/Maison/Maison3/1.png", posx, posy, true));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison3/2.png", posx+50, posy, true));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison3/3.png", posx, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison3/4.png", posx+50, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison3/5.png", posx, posy+100, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison3/6.png", posx+50, posy+100, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison3/7.png", posx, posy+150, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison3/8.png", posx+50, posy+150, false));
    posx=26*50; posy=20*50;
    deco.push_back(new GameTile("./Texture/map/Maison/Maison2/1.png", posx, posy, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison2/2.png", posx+50, posy, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison2/3.png", posx+100, posy, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison2/4.png", posx, posy+50, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison2/5.png", posx+50, posy+50, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison2/6.png", posx+100, posy+50, false));



    posx=100 ;posy=300;
    deco.push_back(new GameTile("./Texture/map/Maison/Maison/1.png", posx, posy, true));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison/2.png", posx+50, posy, true));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison/3.png", posx+100, posy, true));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison/4.png", posx, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison/5.png", posx+50, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison/6.png", posx+100, posy+50, true));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison/7.png", posx, posy+100, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison/8.png", posx+50, posy+100, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison/9.png", posx+100, posy+100, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison/10.png", posx, posy+150, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison/11.png", posx+50, posy+150, false));
    deco.push_back(new GameTile("./Texture/map/Maison/Maison/12.png", posx+100, posy+150, false));

}

void GameWorld::setUpTiles() 
{
    std::vector<GameTile*> ligne1;
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 0, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 50, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 100, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 150, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 200, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 250, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 300, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 350, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 400, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/water.png", 450, 0, false));
    ligne1.push_back(new GameTile("./Texture/map/water.png", 500, 0, false));
    ligne1.push_back(new GameTile("./Texture/map/water.png", 550, 0, false));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 600, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 650, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 700, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 750, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 800, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 850, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 900, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 950, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 1000, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 1050, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 1100, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 1150, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 1200, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 1250, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 1300, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 1350, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 1400, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 1450, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 1500, 0, true));
    ligne1.push_back(new GameTile("./Texture/map/grass.png", 1550, 0, true));
    tiles.push_back(ligne1);

    std::vector<GameTile*> ligne2;
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 0, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 50, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 100, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 150, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 200, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 250, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 300, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 350, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 400, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/water.png", 450, 50, false));
    ligne2.push_back(new GameTile("./Texture/map/water.png", 500, 50, false));
    ligne2.push_back(new GameTile("./Texture/map/water.png", 550, 50, false));
    ligne2.push_back(new GameTile("./Texture/map/water.png", 600, 50, false));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 650, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 700, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 750, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 800, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 850, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 900, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 950, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 1000, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 1050, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 1100, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 1150, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 1200, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 1250, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 1300, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 1350, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 1400, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 1450, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 1500, 50, true));
    ligne2.push_back(new GameTile("./Texture/map/grass.png", 1550, 50, true));
    tiles.push_back(ligne2);

    std::vector<GameTile*> ligne3;
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 0, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 50, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 100, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 150, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 200, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 250, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 300, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 350, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 400, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 450, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/water.png", 500, 100, false));
    ligne3.push_back(new GameTile("./Texture/map/water.png", 550, 100, false));
    ligne3.push_back(new GameTile("./Texture/map/water.png", 600, 100, false));
    ligne3.push_back(new GameTile("./Texture/map/water.png", 650, 100, false));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 700, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 750, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 800, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 850, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 900, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 950, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 1000, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 1050, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 1100, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 1150, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 1200, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 1250, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 1300, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 1350, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 1400, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 1450, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 1500, 100, true));
    ligne3.push_back(new GameTile("./Texture/map/grass.png", 1550, 100, true));
    tiles.push_back(ligne3);

    std::vector<GameTile*> ligne4;
    ligne4.push_back(new GameTile("./Texture/map/grass.png",0,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 50,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 100,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 150,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 200,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 250,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 300,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 350,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 400,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 450,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 500,150, true));
    ligne4.push_back(new GameTile("./Texture/map/water.png", 550,150, false));
    ligne4.push_back(new GameTile("./Texture/map/water.png", 600,150, false));
    ligne4.push_back(new GameTile("./Texture/map/water.png", 650,150, false));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 700,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 750,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 800,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 850,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 900,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 950,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 1000,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 1050,150, true));
    ligne4.push_back(new GameTile("./Texture/map/water.png", 1100,150, false));
    ligne4.push_back(new GameTile("./Texture/map/water.png", 1150,150, false));
    ligne4.push_back(new GameTile("./Texture/map/water.png", 1200,150, false));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 1250,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 1300,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 1350,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 1400,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 1450,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 1500,150, true));
    ligne4.push_back(new GameTile("./Texture/map/grass.png", 1550,150, true));
    tiles.push_back(ligne4);

    std::vector<GameTile*> ligne5;
    ligne5.push_back(new GameTile("./Texture/map/grass.png",0, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",50, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",100, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",150, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",200, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",250, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",300, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",350, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",400, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",450, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",500, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",550, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/water.png",600, 200, false));
    ligne5.push_back(new GameTile("./Texture/map/water.png",650, 200, false));
    ligne5.push_back(new GameTile("./Texture/map/water.png",700, 200, false));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",750, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",800, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",850, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",900, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",950, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",1000, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/water.png",1050, 200, false));
    ligne5.push_back(new GameTile("./Texture/map/water.png",1100, 200, false));
    ligne5.push_back(new GameTile("./Texture/map/water.png",1150, 200, false));
    ligne5.push_back(new GameTile("./Texture/map/water.png",1200, 200, false));
    ligne5.push_back(new GameTile("./Texture/map/water.png",1250, 200, false));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",1300, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",1350, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",1400, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",1450, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",1500, 200, true));
    ligne5.push_back(new GameTile("./Texture/map/grass.png",1550, 200, true));
    tiles.push_back(ligne5);

    std::vector<GameTile*> ligne6;
    ligne6.push_back(new GameTile("./Texture/map/grass.png",0, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",50, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",100, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",150, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",200, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",250, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",300, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",350, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",400, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",450, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",500, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",550, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/water.png",600, 250, false));
    ligne6.push_back(new GameTile("./Texture/map/water.png",650, 250, false));
    ligne6.push_back(new GameTile("./Texture/map/water.png",700, 250, false));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",750, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",800, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",850, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",900, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",950, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/water.png",1000, 250, false));
    ligne6.push_back(new GameTile("./Texture/map/water.png",1050, 250, false));
    ligne6.push_back(new GameTile("./Texture/map/water.png",1100, 250, false));
    ligne6.push_back(new GameTile("./Texture/map/water.png",1150, 250, false));
    ligne6.push_back(new GameTile("./Texture/map/water.png",1200, 250, false));
    ligne6.push_back(new GameTile("./Texture/map/water.png",1250, 250, false));
    ligne6.push_back(new GameTile("./Texture/map/water.png",1300, 250, false));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",1350, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",1400, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",1450, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",1500, 250, true));
    ligne6.push_back(new GameTile("./Texture/map/grass.png",1550, 250, true));
    tiles.push_back(ligne6);

    std::vector<GameTile*> ligne7;
    ligne7.push_back(new GameTile("./Texture/map/grass.png",0, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",50, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",100, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",150, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",200, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",250, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",300, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",350, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",400, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",450, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",500, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",550, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/pond.png",600, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/pond.png",650, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",700, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",750, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",800, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",850, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",900, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/water.png",950, 300, false));
    ligne7.push_back(new GameTile("./Texture/map/water.png",1000, 300, false));
    ligne7.push_back(new GameTile("./Texture/map/water.png",1050, 300, false));
    ligne7.push_back(new GameTile("./Texture/map/water.png",1100, 300, false));
    ligne7.push_back(new GameTile("./Texture/map/water.png",1150, 300, false));
    ligne7.push_back(new GameTile("./Texture/map/water.png",1200, 300, false));
    ligne7.push_back(new GameTile("./Texture/map/water.png",1250, 300, false));
    ligne7.push_back(new GameTile("./Texture/map/water.png",1300, 300, false));
    ligne7.push_back(new GameTile("./Texture/map/water.png",1350, 300, false));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",1400, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",1450, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",1500, 300, true));
    ligne7.push_back(new GameTile("./Texture/map/grass.png",1550, 300, true));
    tiles.push_back(ligne7);

    std::vector<GameTile*> ligne8;
    ligne8.push_back(new GameTile("./Texture/map/grass.png",0, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",50, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",100, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",150, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",200, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",250, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",300, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",350, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",400, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",450, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",500, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",550, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/water.png",600, 350, false));
    ligne8.push_back(new GameTile("./Texture/map/water.png",650, 350, false));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",700, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",750, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",800, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",850, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",900, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/water.png",950, 350, false));
    ligne8.push_back(new GameTile("./Texture/map/water.png",1000, 350, false));
    ligne8.push_back(new GameTile("./Texture/map/water.png",1050, 350, false));
    ligne8.push_back(new GameTile("./Texture/map/water.png",1100, 350, false));
    ligne8.push_back(new GameTile("./Texture/map/water.png",1150, 350, false));
    ligne8.push_back(new GameTile("./Texture/map/water.png",1200, 350, false));
    ligne8.push_back(new GameTile("./Texture/map/water.png",1250, 350, false));
    ligne8.push_back(new GameTile("./Texture/map/water.png",1300, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",1350, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",1400, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",1450, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",1500, 350, true));
    ligne8.push_back(new GameTile("./Texture/map/grass.png",1550, 350, true));
    tiles.push_back(ligne8);

    std::vector<GameTile*> ligne9;
    ligne9.push_back(new GameTile("./Texture/map/grass.png",0, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",50, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",100, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",150, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",200, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",250, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",300, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",350, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",400, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",450, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",500, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/water.png",550, 400, false));
    ligne9.push_back(new GameTile("./Texture/map/water.png",600, 400, false));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",650, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",700, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",750, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",800, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",850, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",900, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/water.png",950, 400, false));
    ligne9.push_back(new GameTile("./Texture/map/water.png",1000, 400, false));
    ligne9.push_back(new GameTile("./Texture/map/water.png",1050, 400, false));
    ligne9.push_back(new GameTile("./Texture/map/water.png",1100, 400, false));
    ligne9.push_back(new GameTile("./Texture/map/water.png",1150, 400, false));
    ligne9.push_back(new GameTile("./Texture/map/water.png",1200, 400, false));
    ligne9.push_back(new GameTile("./Texture/map/water.png",1250, 400, false));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",1300, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",1350, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",1400, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",1450, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",1500, 400, true));
    ligne9.push_back(new GameTile("./Texture/map/grass.png",1550, 400, true));
    tiles.push_back(ligne9);

    std::vector<GameTile*> ligne10;
    ligne10.push_back(new GameTile("./Texture/map/grass.png",0, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",50, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",100, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",150, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",200, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",250, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",300, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",350, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",400, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",450, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/water.png",500, 450, false));
    ligne10.push_back(new GameTile("./Texture/map/water.png",550, 450, false));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",600, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",650, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",700, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",750, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",800, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",850, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",900, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",950, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/water.png",1000, 450, false));
    ligne10.push_back(new GameTile("./Texture/map/water.png",1050, 450, false));
    ligne10.push_back(new GameTile("./Texture/map/water.png",1100, 450, false));
    ligne10.push_back(new GameTile("./Texture/map/water.png",1150, 450, false));
    ligne10.push_back(new GameTile("./Texture/map/water.png",1200, 450, false));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",1250, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",1300, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",1350, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",1400, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",1450, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",1500, 450, true));
    ligne10.push_back(new GameTile("./Texture/map/grass.png",1550, 450, true));
    tiles.push_back(ligne10);

    std::vector<GameTile*> ligne11;
    ligne11.push_back(new GameTile("./Texture/map/grass.png",0, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",50, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",100, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",150, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",200, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",250, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",300, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",350, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",400, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",450, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/water.png",500, 500, false));
    ligne11.push_back(new GameTile("./Texture/map/water.png",550, 500, false));
    ligne11.push_back(new GameTile("./Texture/map/water.png",600, 500, false));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",650, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",700, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",750, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",800, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",850, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",900, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",950, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/water.png",1000, 500, false));
    ligne11.push_back(new GameTile("./Texture/map/water.png",1050, 500, false));
    ligne11.push_back(new GameTile("./Texture/map/water.png",1100, 500, false));
    ligne11.push_back(new GameTile("./Texture/map/pond.png",1150, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/pond.png",1200, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",1250, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",1300, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",1350, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",1400, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",1450, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",1500, 500, true));
    ligne11.push_back(new GameTile("./Texture/map/grass.png",1550, 500, true));
    tiles.push_back(ligne11);

    std::vector<GameTile*> ligne12;
    ligne12.push_back(new GameTile("./Texture/map/grass.png",0, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",50, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",100, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",150, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",200, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",250, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",300, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",350, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",400, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/water.png",450, 550, false));
    ligne12.push_back(new GameTile("./Texture/map/water.png",500, 550, false));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",550, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/water.png",600, 550, false));
    ligne12.push_back(new GameTile("./Texture/map/water.png",650, 550, false));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",700, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",750, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",800, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",850, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",900, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",950, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",1000, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/water.png",1050, 550, false));
    ligne12.push_back(new GameTile("./Texture/map/water.png",1100, 550, false));
    ligne12.push_back(new GameTile("./Texture/map/water.png",1150, 550, false));
    ligne12.push_back(new GameTile("./Texture/map/water.png",1200, 550, false));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",1250, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",1300, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",1350, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",1400, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",1450, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",1500, 550, true));
    ligne12.push_back(new GameTile("./Texture/map/grass.png",1550, 550, true));
    tiles.push_back(ligne12);

    std::vector<GameTile*> ligne13;
    ligne13.push_back(new GameTile("./Texture/map/grass.png",0, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",50, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",100, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",150, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",200, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",250, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",300, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/water.png",350, 600, false));
    ligne13.push_back(new GameTile("./Texture/map/water.png",400, 600, false));
    ligne13.push_back(new GameTile("./Texture/map/water.png",450, 600, false));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",500, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",550, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",600, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/water.png",650, 600, false));
    ligne13.push_back(new GameTile("./Texture/map/water.png",700, 600, false));
    ligne13.push_back(new GameTile("./Texture/map/water.png",750, 600, false));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",800, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",850, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",900, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",950, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",1000, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",1050, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",1100, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",1150, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",1200, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",1250, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",1300, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",1350, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",1400, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",1450, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",1500, 600, true));
    ligne13.push_back(new GameTile("./Texture/map/grass.png",1550, 600, true));
    tiles.push_back(ligne13);

    std::vector<GameTile*> ligne14;
    ligne14.push_back(new GameTile("./Texture/map/grass.png",0, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",50, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",100, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",150, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",200, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",250, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/water.png",300, 650, false));
    ligne14.push_back(new GameTile("./Texture/map/water.png",350, 650, false));
    ligne14.push_back(new GameTile("./Texture/map/water.png",400, 650, false));
    ligne14.push_back(new GameTile("./Texture/map/water.png",450, 650, false));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",500, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",550, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",600, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",650, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",700, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/water.png",750, 650, false));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",800, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",850, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",900, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",950, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",1000, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",1050, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",1100, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",1150, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",1200, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",1250, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",1300, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",1350, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",1400, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",1450, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",1500, 650, true));
    ligne14.push_back(new GameTile("./Texture/map/grass.png",1550, 650, true));
    tiles.push_back(ligne14);

    std::vector<GameTile*> ligne15;
    ligne15.push_back(new GameTile("./Texture/map/grass.png",0, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",50, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",100, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",150, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",200, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",250, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/water.png",300, 700, false));
    ligne15.push_back(new GameTile("./Texture/map/water.png",350, 700, false));
    ligne15.push_back(new GameTile("./Texture/map/water.png",400, 700, false));
    ligne15.push_back(new GameTile("./Texture/map/water.png",450, 700, false));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",500, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",550, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",600, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",650, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",700, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",750, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",800, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",850, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",900, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",950, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",1000, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",1050, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",1100, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",1150, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",1200, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",1250, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",1300, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",1350, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",1400, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",1450, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",1500, 700, true));
    ligne15.push_back(new GameTile("./Texture/map/grass.png",1550, 700, true));
    tiles.push_back(ligne15);

    std::vector<GameTile*> ligne16;
    ligne16.push_back(new GameTile("./Texture/map/grass.png",0, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",50, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",100, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",150, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",200, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",250, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/water.png",300, 750, false));
    ligne16.push_back(new GameTile("./Texture/map/water.png",350, 750, false));
    ligne16.push_back(new GameTile("./Texture/map/water.png",400, 750, false));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",450, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",500, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",550, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",600, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",650, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",700, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",750, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",800, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",850, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",900, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",950, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",1000, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",1050, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",1100, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",1150, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",1200, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",1250, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",1300, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",1350, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",1400, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",1450, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",1500, 750, true));
    ligne16.push_back(new GameTile("./Texture/map/grass.png",1550, 750, true));
    tiles.push_back(ligne16);

    std::vector<GameTile*> ligne17;
    ligne17.push_back(new GameTile("./Texture/map/water.png",0, 800, false));
    ligne17.push_back(new GameTile("./Texture/map/water.png",50, 800, false));
    ligne17.push_back(new GameTile("./Texture/map/water.png",100, 800, false));
    ligne17.push_back(new GameTile("./Texture/map/water.png",150, 800, false));
    ligne17.push_back(new GameTile("./Texture/map/revpond.png",200, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/water.png",250, 800, false));
    ligne17.push_back(new GameTile("./Texture/map/water.png",300, 800, false));
    ligne17.push_back(new GameTile("./Texture/map/water.png",350, 800, false));
    ligne17.push_back(new GameTile("./Texture/map/water.png",400, 800, false));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",450, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",500, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",550, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",600, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",650, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",700, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",750, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",800, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",850, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",900, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",950, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",1000, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",1050, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",1100, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",1150, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",1200, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",1250, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",1300, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",1350, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",1400, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",1450, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",1500, 800, true));
    ligne17.push_back(new GameTile("./Texture/map/grass.png",1550, 800, true));
    tiles.push_back(ligne17);

    std::vector<GameTile*> ligne18;
    ligne18.push_back(new GameTile("./Texture/map/water.png",0, 850, false));
    ligne18.push_back(new GameTile("./Texture/map/water.png",50, 850, false));
    ligne18.push_back(new GameTile("./Texture/map/water.png",100, 850, false));
    ligne18.push_back(new GameTile("./Texture/map/water.png",150, 850, false));
    ligne18.push_back(new GameTile("./Texture/map/revpond.png",200, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/water.png",250, 850, false));
    ligne18.push_back(new GameTile("./Texture/map/water.png",300, 850, false));
    ligne18.push_back(new GameTile("./Texture/map/water.png",350, 850, false));
    ligne18.push_back(new GameTile("./Texture/map/water.png",400, 850, false));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",450, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",500, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",550, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",600, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",650, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",700, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",750, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",800, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",850, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",900, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",950, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",1000, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",1050, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",1100, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",1150, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",1200, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",1250, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",1300, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",1350, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",1400, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",1450, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",1500, 850, true));
    ligne18.push_back(new GameTile("./Texture/map/grass.png",1550, 850, true));
    tiles.push_back(ligne18);

    std::vector<GameTile*> ligne19;
    ligne19.push_back(new GameTile("./Texture/map/grass.png",0, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",50, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",100, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",150, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",200, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",250, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",300, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",350, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/water.png",400, 900, false));
    ligne19.push_back(new GameTile("./Texture/map/water.png",450, 900, false));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",500, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",550, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",600, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",650, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",700, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",750, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",800, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",850, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",900, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",950, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",1000, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",1050, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",1100, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",1150, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",1200, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",1250, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",1300, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",1350, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",1400, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",1450, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",1500, 900, true));
    ligne19.push_back(new GameTile("./Texture/map/grass.png",1550, 900, true));
    tiles.push_back(ligne19);

    std::vector<GameTile*> ligne20;
    ligne20.push_back(new GameTile("./Texture/map/grass.png",0, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",50, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",100, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",150, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",200, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",250, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",300, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",350, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",400, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/water.png",450, 950, false));
    ligne20.push_back(new GameTile("./Texture/map/water.png",500, 950, false));
    ligne20.push_back(new GameTile("./Texture/map/water.png",550, 950, false));
    ligne20.push_back(new GameTile("./Texture/map/water.png",600, 950, false));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",650, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",700, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",750, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",800, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",850, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",900, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",950, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",1000, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",1050, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",1100, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",1150, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",1200, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",1250, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",1300, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",1350, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",1400, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",1450, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",1500, 950, true));
    ligne20.push_back(new GameTile("./Texture/map/grass.png",1550, 950, true));
    tiles.push_back(ligne20);

    std::vector<GameTile*> ligne21;
    ligne21.push_back(new GameTile("./Texture/map/grass.png",0, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",50, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",100, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",150, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",200, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",250, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",300, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",350, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",400, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",450, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/water.png",500, 1000, false));
    ligne21.push_back(new GameTile("./Texture/map/water.png",550, 1000, false));
    ligne21.push_back(new GameTile("./Texture/map/water.png",600, 1000, false));
    ligne21.push_back(new GameTile("./Texture/map/water.png",650, 1000, false));
    ligne21.push_back(new GameTile("./Texture/map/water.png",700, 1000, false));
    ligne21.push_back(new GameTile("./Texture/map/water.png",750, 1000, false));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",800, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",850, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",900, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",950, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",1000, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",1050, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",1100, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",1150, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",1200, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",1250, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",1300, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",1350, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",1400, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",1450, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",1500, 1000, true));
    ligne21.push_back(new GameTile("./Texture/map/grass.png",1550, 1000, true));
    tiles.push_back(ligne21);

    std::vector<GameTile*> ligne22;
    ligne22.push_back(new GameTile("./Texture/map/grass.png",0, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",50, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",100, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",150, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",200, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",250, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",300, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",350, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",400, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",450, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",500, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",550, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",600, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",650, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",700, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",750, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",800, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",850, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",900, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",950, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",1000, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",1050, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",1100, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",1150, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",1200, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",1250, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",1300, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",1350, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",1400, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",1450, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",1500, 1050, true));
    ligne22.push_back(new GameTile("./Texture/map/grass.png",1550, 1050, true));
    tiles.push_back(ligne22);

    std::vector<GameTile*> ligne23;
    ligne23.push_back(new GameTile("./Texture/map/grass.png",0, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",50, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",100, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",150, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",200, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",250, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",300, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",350, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",400, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",450, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",500, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",550, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",600, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",650, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",700, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",750, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",800, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",850, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",900, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",950, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",1000, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",1050, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",1100, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",1150, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",1200, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",1250, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",1300, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",1350, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",1400, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",1450, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",1500, 1100, true));
    ligne23.push_back(new GameTile("./Texture/map/grass.png",1550, 1100, true));
    tiles.push_back(ligne23);

    std::vector<GameTile*> ligne24;
    ligne24.push_back(new GameTile("./Texture/map/grass.png",0, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",50, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",100, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",150, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",200, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",250, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",300, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",350, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",400, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",450, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",500, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",550, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",600, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",650, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",700, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",750, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",800, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",850, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",900, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",950, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",1000, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",1050, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",1100, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",1150, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",1200, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",1250, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",1300, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",1350, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",1400, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",1450, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",1500, 1150, true));
    ligne24.push_back(new GameTile("./Texture/map/grass.png",1550, 1150, true));
    tiles.push_back(ligne24);
}